apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  clusterIP: None  # headless service
  selector:
    app: mysql     # matches the StatefulSet pod labels
  ports:
    - port: 3306
      name: mysql

