apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: wordpress-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-172-31-23-253
      containers:
      - name: mariadb
        image: mariadb:10.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-secret
              key: mariadb-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: wp-config
              key: mariadb-database
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: wp-config
              key: mariadb-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-secret
              key: mariadb-user-password
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-storage
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc
