apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariaadb-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ebs/mariaDb"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2

