apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: wordpress-prod
spec:
  serviceName: mariadb-headless
  replicas: 3
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.6
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-secret
              key: mariadb-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: wp-config
              key: mariadb-database
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: wp-config
              key: mariadb-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-secret
              key: mariadb-user-password
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 2Gi
  volumeClaimTemplates:
  - metadata:
      name: mariadb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
      storageClassName: gp2  # keep as is or change to your storageclass

